import type { Fleet, FleetReport } from "@/lib/types";

export interface PdfReportSummaryLine {
  label: string;
  value: string;
}

export interface PdfReportDocument {
  title: string;
  subtitle: string;
  generatedAt: string;
  summary: PdfReportSummaryLine[];
  periods: {
    periodLabel: string;
    avgSafetyScore: string;
    totalSessions: number;
    totalCriticalAlerts: number;
  }[];
  footerNote: string;
}

/**
 * Pure data-shaping step for the insurer-facing PDF export (PRD Section 8.6).
 * Produces a renderer-agnostic document description; a real PDF library is
 * hidden behind `PdfRenderer` (see below) so this function — the part with
 * actual branching logic — is what's unit-tested, not a PDF binary.
 */
export function shapeFleetReportForPdf(
  fleet: Fleet | null,
  reports: FleetReport[],
  generatedAt: Date = new Date(),
): PdfReportDocument {
  const fleetName = fleet?.name ?? "Unknown fleet";

  if (reports.length === 0) {
    return {
      title: `${fleetName} — Safety Report`,
      subtitle: "No report periods in the selected range",
      generatedAt: generatedAt.toISOString(),
      summary: [],
      periods: [],
      footerNote:
        "Generated by AlertGuard. This report reflects verified driving sessions only.",
    };
  }

  const totalSessions = reports.reduce((sum, r) => sum + (r.total_sessions ?? 0), 0);
  const totalCritical = reports.reduce(
    (sum, r) => sum + (r.total_critical_alerts ?? 0),
    0,
  );
  const scored = reports.filter((r) => r.avg_safety_score !== null && r.avg_safety_score !== undefined);
  const overallAvg =
    scored.length > 0
      ? scored.reduce((sum, r) => sum + (r.avg_safety_score as number), 0) / scored.length
      : null;

  const earliest = reports.reduce((min, r) => (r.period_start < min ? r.period_start : min), reports[0].period_start);
  const latest = reports.reduce((max, r) => (r.period_end > max ? r.period_end : max), reports[0].period_end);

  return {
    title: `${fleetName} — Safety Report`,
    subtitle: `${earliest} to ${latest}`,
    generatedAt: generatedAt.toISOString(),
    summary: [
      { label: "Total verified sessions", value: String(totalSessions) },
      { label: "Total critical alerts", value: String(totalCritical) },
      {
        label: "Average safety score",
        value: overallAvg === null ? "N/A" : overallAvg.toFixed(1),
      },
    ],
    periods: reports.map((r) => ({
      periodLabel: `${r.period_start} – ${r.period_end}`,
      avgSafetyScore: r.avg_safety_score === null || r.avg_safety_score === undefined
        ? "N/A"
        : r.avg_safety_score.toFixed(1),
      totalSessions: r.total_sessions ?? 0,
      totalCriticalAlerts: r.total_critical_alerts ?? 0,
    })),
    footerNote:
      "Generated by AlertGuard. This report reflects verified driving sessions only.",
  };
}

/**
 * Renderer boundary: a real implementation (e.g. pdf-lib, @react-pdf/renderer)
 * turns the shaped document into bytes. Kept as an interface so the data
 * shaping above can be tested without generating a real PDF binary.
 */
export interface PdfRenderer {
  render(doc: PdfReportDocument): Uint8Array;
}

/** Minimal renderer used in demo mode / tests: serializes the doc as UTF-8 JSON bytes. */
export const jsonStubPdfRenderer: PdfRenderer = {
  render(doc: PdfReportDocument): Uint8Array {
    return new TextEncoder().encode(JSON.stringify(doc, null, 2));
  },
};
